INSERT INTO sns_types (
    code, name, display_name, category, input_kind, icon_url,
    url_template, copy_template, placeholder, help_text, sort_order,
    allow_multibyte, normalize_width, is_active
) VALUES
    ('line', 'LINE', 'LINE', 'standard', 'text', 'https://cdn.simpleicons.org/line', 'https://line.me/ti/p/{value}', '{value}', 'LINE ID または共有URL', 'LINE ID または共有URLを入力', 10, TRUE, TRUE, TRUE),
    ('instagram', 'Instagram', 'Instagram', 'standard', 'handle', 'https://cdn.simpleicons.org/instagram', 'https://instagram.com/{value}', '@{value}', 'username', '@なしで入力', 20, FALSE, TRUE, TRUE),
    ('x', 'X', 'X', 'standard', 'handle', 'https://cdn.simpleicons.org/x', 'https://x.com/{value}', '@{value}', 'username', '@なしで入力', 30, FALSE, TRUE, TRUE),
    ('note', 'note', 'note', 'standard', 'handle', 'https://cdn.simpleicons.org/note', 'https://note.com/{value}', '{value}', 'note ID', 'noteのユーザーIDを入力', 40, FALSE, TRUE, TRUE),
    ('website', 'Website', 'Webサイト', 'standard', 'url', 'https://cdn.jsdelivr.net/npm/lucide-static@0.468.0/icons/globe.svg', '{value}', '{value}', 'https://example.com', 'URLを入力', 50, TRUE, TRUE, TRUE),
    ('email', 'Email', 'メール', 'standard', 'email', 'https://cdn.jsdelivr.net/npm/lucide-static@0.468.0/icons/mail.svg', 'mailto:{value}', '{value}', 'name@example.com', 'メールアドレスを入力', 60, FALSE, TRUE, TRUE),
    ('youtube', 'YouTube', 'YouTube', 'activity', 'url', 'https://cdn.simpleicons.org/youtube', '{value}', '{value}', 'https://youtube.com/@channel', 'チャンネルURLを入力', 110, TRUE, TRUE, TRUE),
    ('tiktok', 'TikTok', 'TikTok', 'activity', 'handle', 'https://cdn.simpleicons.org/tiktok', 'https://www.tiktok.com/@{value}', '@{value}', 'username', '@なしで入力', 120, FALSE, TRUE, TRUE),
    ('threads', 'Threads', 'Threads', 'activity', 'handle', 'https://cdn.simpleicons.org/threads', 'https://www.threads.net/@{value}', '@{value}', 'username', '@なしで入力', 130, FALSE, TRUE, TRUE),
    ('bluesky', 'Bluesky', 'Bluesky', 'activity', 'handle', 'https://cdn.simpleicons.org/bluesky', 'https://bsky.app/profile/{value}', '{value}', 'handle.bsky.social', 'Blueskyのハンドルを入力', 140, FALSE, TRUE, TRUE),
    ('facebook', 'Facebook', 'Facebook', 'activity', 'url', 'https://cdn.simpleicons.org/facebook', '{value}', '{value}', 'https://facebook.com/yourname', 'プロフィールURLを入力', 150, TRUE, TRUE, TRUE),
    ('seventeen-live', '17LIVE', '17LIVE', 'live', 'url', 'https://17.live/favicon.ico', '{value}', '{value}', 'https://17.live/...', 'プロフィールURLを入力', 210, TRUE, TRUE, TRUE),
    ('showroom', 'SHOWROOM', 'SHOWROOM', 'live', 'url', 'https://www.showroom-live.com/favicon.ico', '{value}', '{value}', 'https://www.showroom-live.com/...', 'プロフィールURLを入力', 220, TRUE, TRUE, TRUE),
    ('pococha', 'Pococha', 'Pococha', 'live', 'url', 'https://www.pococha.com/favicon.ico', '{value}', '{value}', 'https://www.pococha.com/...', 'プロフィールURLを入力', 230, TRUE, TRUE, TRUE),
    ('twitcasting', 'TwitCasting', 'ツイキャス', 'live', 'handle', 'https://twitcasting.tv/favicon.ico', 'https://twitcasting.tv/{value}', '{value}', 'screen name', 'ツイキャスIDまたはURLを入力', 240, FALSE, TRUE, TRUE),
    ('litlink', 'lit.link', 'lit.link', 'activity', 'url', 'https://lit.link/favicon.ico', '{value}', '{value}', 'https://lit.link/yourname', 'lit.link URLを入力', 250, TRUE, TRUE, TRUE),
    ('linktree', 'Linktree', 'Linktree', 'activity', 'url', 'https://cdn.simpleicons.org/linktree', '{value}', '{value}', 'https://linktr.ee/yourname', 'Linktree URLを入力', 260, TRUE, TRUE, TRUE),
    ('linkedin', 'LinkedIn', 'LinkedIn', 'work', 'url', 'https://cdn.simpleicons.org/linkedin', '{value}', '{value}', 'https://www.linkedin.com/in/yourname', 'プロフィールURLを入力', 310, TRUE, TRUE, TRUE),
    ('wantedly', 'Wantedly', 'Wantedly', 'work', 'url', 'https://www.wantedly.com/favicon.ico', '{value}', '{value}', 'https://www.wantedly.com/id/yourname', 'プロフィールURLを入力', 320, TRUE, TRUE, TRUE),
    ('qiita', 'Qiita', 'Qiita', 'developer', 'handle', 'https://cdn.simpleicons.org/qiita', 'https://qiita.com/{value}', '{value}', 'username', 'Qiita ID またはURLを入力', 330, FALSE, TRUE, TRUE),
    ('zenn', 'Zenn', 'Zenn', 'developer', 'handle', 'https://cdn.simpleicons.org/zenn', 'https://zenn.dev/{value}', '{value}', 'username', 'Zenn ID またはURLを入力', 340, FALSE, TRUE, TRUE),
    ('github', 'GitHub', 'GitHub', 'developer', 'handle', 'https://cdn.simpleicons.org/github', 'https://github.com/{value}', '{value}', 'username', 'GitHub ID またはURLを入力', 350, FALSE, TRUE, TRUE),
    ('speakerdeck', 'Speaker Deck', 'Speaker Deck', 'work', 'handle', 'https://cdn.simpleicons.org/speakerdeck', 'https://speakerdeck.com/{value}', '{value}', 'username', 'Speaker Deck ID またはURLを入力', 360, FALSE, TRUE, TRUE),
    ('connpass', 'connpass', 'connpass', 'work', 'handle', 'https://connpass.com/favicon.ico', 'https://connpass.com/user/{value}', '{value}', 'username', 'connpass ID またはURLを入力', 370, FALSE, TRUE, TRUE),
    ('discord', 'Discord', 'Discord', 'community', 'text', 'https://cdn.simpleicons.org/discord', '{value}', '{value}', 'ユーザー名 または 招待URL', 'Discordのユーザー名または招待URLを入力', 410, TRUE, TRUE, TRUE),
    ('twitch', 'Twitch', 'Twitch', 'community', 'handle', 'https://cdn.simpleicons.org/twitch', 'https://www.twitch.tv/{value}', '{value}', 'username', 'Twitch ID またはURLを入力', 420, FALSE, TRUE, TRUE),
    ('reddit', 'Reddit', 'Reddit', 'community', 'handle', 'https://cdn.simpleicons.org/reddit', 'https://www.reddit.com/user/{value}', 'u/{value}', 'username', 'Reddit ID またはURLを入力', 430, FALSE, TRUE, TRUE),
    ('mastodon', 'Mastodon', 'Mastodon', 'community', 'url', 'https://cdn.simpleicons.org/mastodon', '{value}', '{value}', 'https://mastodon.social/@yourname', 'プロフィールURLを入力', 440, TRUE, TRUE, TRUE),
    ('phone', 'Phone', '電話', 'contact', 'phone', 'https://cdn.jsdelivr.net/npm/lucide-static@0.468.0/icons/phone.svg', 'tel:{value}', '{value}', '090-0000-0000', '電話番号を入力', 510, FALSE, TRUE, TRUE),
    ('other', 'Other', 'その他', 'other', 'text', 'https://cdn.jsdelivr.net/npm/lucide-static@0.468.0/icons/link.svg', '{value}', '{value}', 'https://example.com', '自由入力', 900, TRUE, TRUE, TRUE)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    display_name = EXCLUDED.display_name,
    category = EXCLUDED.category,
    input_kind = EXCLUDED.input_kind,
    icon_url = EXCLUDED.icon_url,
    url_template = EXCLUDED.url_template,
    copy_template = EXCLUDED.copy_template,
    placeholder = EXCLUDED.placeholder,
    help_text = EXCLUDED.help_text,
    sort_order = EXCLUDED.sort_order,
    allow_multibyte = EXCLUDED.allow_multibyte,
    normalize_width = EXCLUDED.normalize_width,
    is_active = EXCLUDED.is_active,
    updated_at = CURRENT_TIMESTAMP;
