BEGIN;

CREATE TABLE IF NOT EXISTS share_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    public_token VARCHAR(64) NOT NULL UNIQUE,
    body TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ready',
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    location_accuracy_m DOUBLE PRECISION,
    location_captured_at TIMESTAMPTZ,
    expires_in VARCHAR(10) NOT NULL DEFAULT '24h',
    first_accessed_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS share_event_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    share_event_id BIGINT NOT NULL REFERENCES share_events(id) ON DELETE CASCADE,
    storage_path TEXT NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    file_size INTEGER NOT NULL,
    width INTEGER,
    height INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS share_access_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    share_event_id BIGINT NOT NULL REFERENCES share_events(id) ON DELETE CASCADE,
    profile_id BIGINT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    viewer_token VARCHAR(128),
    access_ip_hash VARCHAR(128),
    user_agent TEXT,
    accessed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reserved_share_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    profile_id BIGINT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    public_token VARCHAR(64) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'available',
    reserved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_share_events_profile_id ON share_events(profile_id);
CREATE INDEX IF NOT EXISTS idx_share_event_photos_share_event_id ON share_event_photos(share_event_id);
CREATE INDEX IF NOT EXISTS idx_share_access_logs_profile_id ON share_access_logs(profile_id);
CREATE INDEX IF NOT EXISTS idx_reserved_share_tokens_profile_id ON reserved_share_tokens(profile_id);
CREATE INDEX IF NOT EXISTS idx_reserved_share_tokens_status ON reserved_share_tokens(status);

COMMIT;
