BEGIN;

CREATE TABLE IF NOT EXISTS guest_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    share_event_id BIGINT REFERENCES share_events(id) ON DELETE SET NULL,
    guest_name VARCHAR(120) NOT NULL,
    message TEXT NOT NULL,
    recipient_email VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_guest_messages_profile_id ON guest_messages(profile_id);
CREATE INDEX IF NOT EXISTS idx_guest_messages_share_event_id ON guest_messages(share_event_id);

COMMIT;
