BEGIN;

ALTER TABLE sns_types
    ADD COLUMN IF NOT EXISTS display_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS category VARCHAR(50) NOT NULL DEFAULT 'standard',
    ADD COLUMN IF NOT EXISTS input_kind VARCHAR(30) NOT NULL DEFAULT 'text',
    ADD COLUMN IF NOT EXISTS url_template TEXT,
    ADD COLUMN IF NOT EXISTS copy_template TEXT,
    ADD COLUMN IF NOT EXISTS placeholder VARCHAR(255),
    ADD COLUMN IF NOT EXISTS help_text TEXT,
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS allow_multibyte BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS normalize_width BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE profile_sns
    ADD COLUMN IF NOT EXISTS raw_value TEXT;

COMMIT;
